import React, { useMemo, useState } from 'react';
import { Activity, AlertTriangle, BookOpen, Check, LocateFixed, MessageSquare, Phone, Search, ShieldAlert, Users, Clock3, X, Play, RotateCcw, Radio, FlaskConical, Shuffle, MapPin } from 'lucide-react';

const seed = [
 {id:'STU1024',name:'Srinesh G',department:'AIML',year:'II Year',attendance:'Absent',campus:true,classPresent:false,zone:'C Block Ãƒâ€šÃ‚Â· Floor 2',lastSeen:'10:24 AM',gate:'North Gate',points:0},
 {id:'STU1025',name:'Kavin R',department:'AIML',year:'II Year',attendance:'Present',campus:true,classPresent:true,zone:'A Block Ãƒâ€šÃ‚Â· Room 101',lastSeen:'10:31 AM',gate:'North Gate',points:0},
 {id:'STU1026',name:'Divya S',department:'AIML',year:'I Year',attendance:'On Duty',campus:true,classPresent:false,zone:'Library Ãƒâ€šÃ‚Â· Floor 3',lastSeen:'10:18 AM',gate:'South Gate',points:0},
 {id:'STU1027',name:'Arjun M',department:'AIML',year:'III Year',attendance:'Present',campus:true,classPresent:true,zone:'C Block Ãƒâ€šÃ‚Â· Room 202',lastSeen:'10:33 AM',gate:'South Gate',points:0},
 {id:'STU1028',name:'Nithya P',department:'AIML',year:'II Year',attendance:'Absent',campus:false,classPresent:false,zone:'Last seen: Main Gate',lastSeen:'9:06 AM',gate:'North Gate',points:1},
 {id:'STU1029',name:'Harish V',department:'AIML',year:'III Year',attendance:'Present',campus:true,classPresent:false,zone:'A Block Ãƒâ€šÃ‚Â· Floor 1',lastSeen:'10:28 AM',gate:'North Gate',points:0}
];
const initials=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2);
const zones=['A Block Ãƒâ€šÃ‚Â· Room 101','A Block Ãƒâ€šÃ‚Â· Floor 1','B Block Ãƒâ€šÃ‚Â· Lab 2','C Block Ãƒâ€šÃ‚Â· Floor 2','C Block Ãƒâ€šÃ‚Â· Room 202','Library Ãƒâ€šÃ‚Â· Floor 3','Cafeteria','Sports Ground','Main Gate'];
const timeNow=()=>new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'});
export default function App(){
 const [students,setStudents]=useState(seed),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[sortBy,setSortBy]=useState('name'),[attendanceHistory,setAttendanceHistory]=useState([]),[checks,setChecks]=useState({}),[active,setActive]=useState(null),[message,setMessage]=useState(''),[notice,setNotice]=useState(''),[pointsReason,setPointsReason]=useState('Unexplained class absence'),[pointsToAdd,setPointsToAdd]=useState('1'),[logs,setLogs]=useState([{time:timeNow(),text:'Dashboard opened',detail:'Attendance workspace ready'}]),[tick,setTick]=useState(1),[scenario,setScenario]=useState('campus_no_class'),[running,setRunning]=useState(false);
 const visible=useMemo(()=>students.filter(s=>(s.id+' '+s.name+' '+s.department).toLowerCase().includes(query.toLowerCase())&&(filter==='All'||s.attendance===filter)).sort((a,b)=>sortBy==='name'?a.name.localeCompare(b.name):sortBy==='department'?a.department.localeCompare(b.department):sortBy==='attendance'?a.attendance.localeCompare(b.attendance):a.id.localeCompare(b.id)),[students,query,filter,sortBy]);
 const addLog=(text,detail)=>setLogs(old=>[{time:timeNow(),text,detail},...old].slice(0,8));
 const update=(id,patch)=>setStudents(old=>old.map(s=>s.id===id?{...s,...patch}:s));
 const notify=text=>{setNotice(text);setTimeout(()=>setNotice(''),2800)};
 const exportCsv=()=>{const rows=[['Student ID','Name','Department','Year','Attendance','Gate','Last Seen','Zone','Violation Points'],...students.map(s=>[s.id,s.name,s.department,s.year,s.attendance,s.gate,s.lastSeen,s.zone,s.points])];const csv=rows.map(row=>row.map(value=>'"'+String(value??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='encontrar-attendance.csv';a.click();URL.revokeObjectURL(url);notify('Attendance CSV exported.');};
 const undoAttendance=()=>{if(!attendanceHistory.length)return;const previous=attendanceHistory[attendanceHistory.length-1];update(previous.id,{attendance:previous.attendance});setChecks(old=>({...old,[previous.id]:previous.check??null}));setAttendanceHistory(old=>old.slice(0,-1));addLog('Attendance change undone',previous.id+' · Restored previous status');notify('Last attendance change undone.');};
 const simulate=(s,mode=scenario)=>{
   const zone=zones[Math.floor(Math.random()*zones.length)], lastSeen=timeNow(), gate=Math.random()>.5?'North Gate':'South Gate';
   let campus=true,classPresent=false,attendance=s.attendance,reason='';
   if(mode==='campus_no_class'){campus=true;classPresent=false;reason='Gate entry detected; no classroom check-in recorded for the scheduled class.'}
   if(mode==='off_campus'){campus=false;classPresent=false;reason='No campus entry recorded for this student.'}
   if(mode==='normal'){campus=true;classPresent=true;reason='Gate and classroom check-in both detected.'}
   if(mode==='random'){campus=Math.random()>.28;classPresent=campus&&Math.random()>.42;reason=campus?(classPresent?'Class check-in recorded.':'On campus, but no classroom check-in recorded.'):'No campus entry recorded.'}
   if(!campus){attendance='Absent'}
   const confidence=Number((0.72+Math.random()*0.25).toFixed(2));
   const result={student_id:s.id,status:campus&&!classPresent?'exception_flagged':(!campus?'no_gate_presence':'normal'),model_available:false,simulation:true,confidence,campus_present:campus,class_present:classPresent,zone:campus?zone:'Last seen: '+gate,last_seen:lastSeen,gate_id:gate,source:'Campus activity records',reason};
   update(s.id,{campus,classPresent,zone:result.zone,lastSeen,gate,attendance:attendance==='On Duty'?'On Duty':attendance});
   setChecks(old=>({...old,[s.id]:result}));setTick(n=>n+1);
   addLog('Attendance review completed',s.id+' Ãƒâ€šÃ‚Â· '+(campus?(classPresent?'Campus + class':'Campus, not in class'):'No campus entry recorded'));
   return result;
 };
 function mark(s,status){setAttendanceHistory(old=>[...old.slice(-19),{id:s.id,attendance:s.attendance,check:checks[s.id]}]);update(s.id,{attendance:status});addLog('Attendance marked '+status,s.id+' Ãƒâ€šÃ‚Â· Faculty action');if(status!=='Absent'){setChecks(old=>({...old,[s.id]:null}));return}simulate({...s,attendance:status},scenario);}
 function runScenario(){setRunning(true);const targets=students.filter(s=>s.attendance==='Absent');const list=targets.length?targets:[students[0]];list.forEach(s=>simulate(s,scenario));addLog('Attendance review completed',scenarioLabel(scenario)+' Ãƒâ€šÃ‚Â· '+list.length+' student record(s) reviewed');setRunning(false);notify('Attendance review completed.');}
 function scenarioLabel(key){return ({campus_no_class:'On campus, outside class',off_campus:'No campus entry recorded',normal:'Normal attendance',random:'Mixed random activity'})[key]||key}
 function applyScenarioToAll(){const next=students.map(s=>{let campus=true,classPresent=true,zone=zones[Math.floor(Math.random()*zones.length)],gate=Math.random()>.5?'North Gate':'South Gate';if(scenario==='campus_no_class')classPresent=false;if(scenario==='off_campus'){campus=false;classPresent=false}if(scenario==='random'){campus=Math.random()>.28;classPresent=campus&&Math.random()>.42}return {...s,campus,classPresent,zone:campus?zone:'Last seen: '+gate,lastSeen:timeNow(),gate,attendance:s.attendance}});setStudents(next);const newChecks={};next.forEach(s=>{newChecks[s.id]={student_id:s.id,status:s.campus&&!s.classPresent?'exception_flagged':!s.campus?'no_gate_presence':'normal',model_available:false,simulation:true,confidence:Number((.72+Math.random()*.25).toFixed(2)),campus_present:s.campus,class_present:s.classPresent,zone:s.zone,last_seen:s.lastSeen,gate_id:s.gate,source:'Campus activity records',reason:s.campus?(s.classPresent?'Class check-in recorded.':'On campus but no classroom check-in.'):'No campus entry recorded.'}});setChecks(newChecks);setTick(n=>n+1);addLog('Scenario applied to all students',scenarioLabel(scenario));notify('Campus activity updated.')}
 function reset(){setStudents(seed.map(s=>({...s})));setChecks({});setLogs([{time:timeNow(),text:'Dashboard reset',detail:'Restored the initial student records'}]);setTick(1);notify('Dashboard reset to initial state.')}
 function doAction(type,student){setActive({type,student});if(type==='message')setMessage('');if(type==='points')setPointsToAdd('1');if(type==='location')addLog('Location details opened',student.id+' Ãƒâ€šÃ‚Â· latest available record')}
 function submitAction(){const type=active.type,s=active.student;if(type==='message'&&!message.trim())return;if(type==='points'){const n=Math.max(1,Math.min(10,Number(pointsToAdd)||1));update(s.id,{points:s.points+n});addLog('Violation points added',s.id+' Ãƒâ€šÃ‚Â· +'+n+' Ãƒâ€šÃ‚Â· '+pointsReason);notify(n+' point(s) added to '+s.id)}else if(type==='message'){addLog('Message draft saved',s.id+' Ãƒâ€šÃ‚Â· '+message.trim());notify('Message draft saved.')}else if(type==='call')notify('Call action recorded.');setActive(null)}
 const flagged=students.filter(s=>s.attendance==='Absent'&&checks[s.id]?.campus_present&&!checks[s.id]?.class_present);
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-logo">e</div><div><strong>encontrar<span>.</span></strong><small>FACULTY DASHBOARD</small></div></div><div className="side-label">WORKSPACE</div><div className="side-active"><Activity size={17}/> Attendance & students</div><div className="side-bottom"><span className="online-dot"/>{' '}Workspace ready</div></aside>
 <main className="main"><header className="topbar"><div><div className="crumb">Campus / <b>Attendance</b></div><h1>Student attendance</h1><p>Manage attendance, review campus activity, and follow up when needed.</p></div><div className="faculty"><div className="faculty-avatar">FM</div><div><b>Faculty Member</b><small>Faculty access</small></div></div></header><section className="content">
 <div className="stats"><div className="stat"><span className="stat-icon blue"><Users size={18}/></span><div><small>Students</small><strong>{students.length}</strong></div></div><div className="stat"><span className="stat-icon green"><Check size={18}/></span><div><small>Marked present</small><strong>{students.filter(s=>s.attendance==='Present').length}</strong></div></div><div className="stat"><span className="stat-icon amber"><AlertTriangle size={18}/></span><div><small>Marked absent</small><strong>{students.filter(s=>s.attendance==='Absent').length}</strong></div></div><div className="stat"><span className="stat-icon violet"><LocateFixed size={18}/></span><div><small>Needs follow-up</small><strong>{flagged.length}</strong></div></div></div>
 <div className="workflow"><div className="workflow-icon"><Activity size={19}/></div><div><b>Faculty workflow</b><p>Mark a student <b>Absent</b> to review campus activity. If the latest records suggest a mismatch, location details and follow-up actions become available.</p></div></div>
 <div className="toolbar"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, student ID, department"/></div><div className="filters">{['All','Present','Absent','On Duty'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="toolbar-tools"><select aria-label="Sort students" value={sortBy} onChange={e=>setSortBy(e.target.value)}><option value="name">Sort: Name</option><option value="department">Sort: Department</option><option value="attendance">Sort: Attendance</option><option value="id">Sort: Student ID</option></select><button className="action-btn" onClick={exportCsv}>Export CSV</button><button className="action-btn" onClick={undoAttendance} disabled={!attendanceHistory.length} title="Undo the last attendance status change">Undo</button></div></div>
 <div className="table-card"><div className="table-scroll"><table><thead><tr><th>STUDENT</th><th>DEPARTMENT</th><th>ATTENDANCE STATUS</th><th>REVIEW GATE / ZONE</th><th>FOLLOW-UP ACTIONS</th></tr></thead><tbody>{visible.map(s=>{const c=checks[s.id];const mismatch=s.attendance==='Absent'&&c?.campus_present&&!c?.class_present;return <React.Fragment key={s.id}><tr><td><div className="student"><div className="student-avatar">{initials(s.name)}</div><div><b>{s.name}</b><small>{s.id} Ãƒâ€šÃ‚Â· {s.year}</small></div></div></td><td><span className="dept">{s.department}</span></td><td><div className="status-buttons">{['Present','Absent','On Duty'].map(status=><button key={status} className={status.toLowerCase().replace(' ','-')+(s.attendance===status?' chosen':'')} onClick={()=>mark(s,status)}>{status}</button>)}</div>{c&&<div className={'result '+(c.simulation?'demo-result':'')}><span className="result-dot"/><span>{c.campus_present?'Campus entry found':'No campus entry recorded'}{c.campus_present&&c.class_present?' Ãƒâ€šÃ‚Â· Class check-in':c.campus_present?' Ãƒâ€šÃ‚Â· Not in class':''}</span></div>}</td><td><div className="last-seen"><b>{s.gate}</b><small><Clock3 size={12}/>{s.lastSeen}</small><small><MapPin size={12}/>{s.zone}</small></div></td><td>{mismatch?<div className="actions"><button className="action-btn location" onClick={()=>doAction('location',s)}><LocateFixed size={14}/> Location</button><button className="action-btn" title="Call student" onClick={()=>doAction('call',s)}><Phone size={14}/></button><button className="action-btn" title="Simulate message" onClick={()=>doAction('message',s)}><MessageSquare size={14}/></button><button className="action-btn points" onClick={()=>doAction('points',s)}><ShieldAlert size={14}/> Points</button></div>:<span className="muted">{s.attendance==='On Duty'?'Duty exemption':s.attendance==='Absent'?(c?'No campus mismatch found':'Mark absent to review campus activity'):'No action required'}</span>}</td></tr>{mismatch&&<tr className="detail-row"><td colSpan="5"><div className="detail-banner"><LocateFixed size={15}/><div><b>{s.name} is may be on campus but outside the scheduled class</b><small>{c.zone} · Last recorded event {c.last_seen} · {c.reason}</small></div><span className="demo-tag">REVIEW</span></div></td></tr>}</React.Fragment>})}</tbody></table>{visible.length===0&&<div className="empty">No students match this search.</div>}</div><div className="table-footer"><span>Showing {visible.length} of {students.length} students</span><span><span className="online-dot"/>{' '}Changes stay in this browser session</span></div></div>
 <div className="bottom-grid"><section className="card"><div className="card-heading"><div><h2>Recent activity</h2><p>Attendance updates and faculty follow-ups</p></div><Activity size={17}/></div>{logs.slice(0,6).map((l,i)=><div className="log" key={i}><span className="log-dot"/><div><b>{l.text.replace('Attendance review completed','Attendance review completed').replace('Attendance review completed','Attendance review completed').replace('Dashboard opened','Dashboard opened').replace('Dashboard reset','Dashboard reset').replace('Violation points added','Violation points added').replace('Message draft saved','Message draft saved').replace('Location details opened','Location details opened')}</b><small>{l.detail.replace('Attendance workspace ready','Attendance workspace ready').replace(' Ãƒâ€šÃ‚Â· ','').replace(' Ãƒâ€šÃ‚Â· latest available record','')}</small></div><time>{l.time}</time></div>)}</section></div></section></main>
 {active&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setActive(null)}}><section className="modal"><div className="modal-head"><div><span className="modal-kicker">REVIEW STUDENT FOLLOW-UP</span><h2>{active.type==='location'?'Location details':active.type==='call'?'Call student':active.type==='message'?'Send a message':'Add violation points'}</h2></div><button className="close" onClick={()=>setActive(null)}><X size={18}/></button></div><div className="modal-student"><div className="student-avatar big">{initials(active.student.name)}</div><div><b>{active.student.name}</b><small>{active.student.id} Ãƒâ€šÃ‚Â· {active.student.department} Ãƒâ€šÃ‚Â· {active.student.year}</small></div></div>
 {active.type==='location'&&<><div className="location-grid"><div><small>Last known zone</small><b>{checks[active.student.id]?.zone||active.student.zone}</b></div><div><small>Last recorded event</small><b>{checks[active.student.id]?.last_seen||active.student.lastSeen}</b></div><div><small>Gate</small><b>{checks[active.student.id]?.gate_id||active.student.gate}</b></div><div><small>Data source</small><b>Campus activity records</b></div></div><div className="notice-box">Location details reflect the latest available record and should be verified before follow-up.</div></>}
 {active.type==='call'&&<div className="notice-box">Confirm the studentÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s contact details before placing a call.</div>}
 {active.type==='message'&&<label className="form-label">Message<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Please report to your faculty member regarding today's attendanceÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦" rows="4"/></label>}
 {active.type==='points'&&<><label className="form-label">Points to add<select value={pointsToAdd} onChange={e=>setPointsToAdd(e.target.value)}>{[1,2,3,5,10].map(n=><option key={n} value={n}>{n} point{n>1?'s':''}</option>)}</select></label><label className="form-label">Reason<select value={pointsReason} onChange={e=>setPointsReason(e.target.value)}><option>Unexplained class absence</option><option>Repeated late arrival</option><option>Faculty-reviewed policy violation</option><option>Other ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â faculty review</option></select></label><div className="notice-box">Please verify the circumstances and follow institutional policy before assigning points.</div></>}
 <div className="modal-actions"><button className="cancel" onClick={()=>setActive(null)}>Cancel</button>{active.type!=='location'&&<button className="confirm" onClick={submitAction}>{active.type==='call'?'Record call':active.type==='message'?'Save message':'Add points'}</button>}{active.type==='location'&&<button className="confirm" onClick={()=>{addLog('Location details reviewed',active.student.id+' Ãƒâ€šÃ‚Â· ');setActive(null);notify('Location details reviewed.')}}>Done</button>}</div></section></div>}
 {notice&&<div className="toast"><Check size={16}/>{notice}</div>}</div>
}