import React, { useMemo, useState } from 'react';
import {
  Activity, AlertCircle, ArrowDownRight, ArrowRight, Bell, BookOpen, CalendarDays, Camera,
  Check, CheckCircle2, ChevronDown, ChevronRight, CircleHelp, Clock3, Command, DoorOpen,
  Download, ExternalLink, Eye, FileText, Filter, Fingerprint, GraduationCap, LayoutDashboard,
  LifeBuoy, LocateFixed, LogOut, MapPin, Menu, MessageSquare, MoreHorizontal, Search, Send,
  Settings, Shield, ShieldCheck, Smartphone, UserCheck, UserRound, Users, Wifi, X, Zap,
  RadioTower, ChartNoAxesCombined, CircleDot, ClipboardCheck, Phone, Ban, CheckCheck
} from 'lucide-react';
import {
  Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis,
  BarChart, Bar
} from 'recharts';

const initialStudents = [
  { id:'STU1024', name:'Srinesh G', initials:'SG', dept:'AIML', year:'II Year', room:'C Block · Floor 2', lastSeen:'10:24 AM', zone:'C Block', campus:true, attendance:'Absent', duty:false, confidence:'High', points:85, color:'violet', camera:'Corridor C2', source:'Wi-Fi + last observation' },
  { id:'STU1025', name:'Kavin R', initials:'KR', dept:'CSE', year:'II Year', room:'Main Building · Floor 1', lastSeen:'10:31 AM', zone:'Main Building', campus:true, attendance:'Present', duty:false, confidence:'High', points:96, color:'blue', camera:'—', source:'Staff attendance' },
  { id:'STU1026', name:'Divya S', initials:'DS', dept:'AIML', year:'I Year', room:'Library · Floor 3', lastSeen:'10:18 AM', zone:'Library', campus:true, attendance:'Absent', duty:true, confidence:'Medium', points:100, color:'rose', camera:'—', source:'Approved on-duty' },
  { id:'STU1027', name:'Arjun M', initials:'AM', dept:'ECE', year:'III Year', room:'Canteen · Ground', lastSeen:'10:33 AM', zone:'Canteen', campus:true, attendance:'Present', duty:false, confidence:'High', points:92, color:'amber', camera:'—', source:'Staff attendance' },
  { id:'STU1028', name:'Nithya P', initials:'NP', dept:'IT', year:'II Year', room:'—', lastSeen:'9:06 AM', zone:'Last seen: Main gate', campus:false, attendance:'Absent', duty:false, confidence:'Medium', points:88, color:'green', camera:'—', source:'RFID exit event' },
  { id:'STU1029', name:'Harish V', initials:'HV', dept:'AIML', year:'III Year', room:'A Block · Floor 1', lastSeen:'10:28 AM', zone:'A Block', campus:true, attendance:'Absent', duty:false, confidence:'Low', points:79, color:'cyan', camera:'—', source:'Wi-Fi observation' },
];

const weekly = [
  { day:'Mon', present:88, absent:12 }, { day:'Tue', present:92, absent:8 },
  { day:'Wed', present:85, absent:15 }, { day:'Thu', present:94, absent:6 },
  { day:'Fri', present:89, absent:11 }, { day:'Sat', present:96, absent:4 },
  { day:'Today', present:91, absent:9 },
];
const trend = [
 {time:'08:00', entries:142}, {time:'08:30',entries:384}, {time:'09:00',entries:721},
 {time:'09:30',entries:890}, {time:'10:00',entries:1032}, {time:'10:30',entries:1098}, {time:'11:00',entries:1120}
];
const navGroups = [
 {label:'WORKSPACE', items:[['Overview',LayoutDashboard],['Student directory',Users],['Attendance',ClipboardCheck],['Location requests',LocateFixed],['Campus map',MapPin]]},
 {label:'OPERATIONS',items:[['Entry & exit',DoorOpen],['Camera access',Camera],['Points & policies',ShieldCheck],['Activity logs',Activity]]},
 {label:'SYSTEM',items:[['Integrations',RadioTower],['Settings',Settings]]}
];

function Avatar({student,size='md'}) { return <div className={`avatar ${student?.color||'blue'} ${size}`}><span>{student?.initials||'?'}</span></div>; }
function Badge({children,tone='neutral',dot=false}) { return <span className={`badge ${tone}`}>{dot&&<i/>}{children}</span>; }
function Panel({children,className=''}) { return <section className={`panel ${className}`}>{children}</section>; }
function PanelHead({title,sub,action}) { return <div className="panel-head"><div><h3>{title}</h3>{sub&&<p>{sub}</p>}</div>{action}</div>; }

export default function App(){
 const [page,setPage] = useState('Overview');
 const [students,setStudents] = useState(initialStudents);
 const [query,setQuery] = useState('');
 const [filter,setFilter] = useState('All students');
 const [selected,setSelected] = useState(initialStudents[0]);
 const [toast,setToast] = useState('');
 const [modal,setModal] = useState(null);
 const [requestReason,setRequestReason] = useState('Absent from class but reported on campus');
 const [role,setRole] = useState('Faculty');
 const [alerts,setAlerts] = useState(true);
 const [sidebarOpen,setSidebarOpen] = useState(false);
 const [range,setRange] = useState('Today');
 const [activity,setActivity] = useState([
  {time:'10:34:18',title:'Location review requested',detail:'STU1024 · Machine Learning · Faculty initiated',tone:'blue'},
  {time:'10:31:02',title:'RFID entry event',detail:'Main gate · 4 cards detected in batch',tone:'green'},
  {time:'10:28:41',title:'On-duty status approved',detail:'STU1026 · Department activity',tone:'violet'},
  {time:'10:24:07',title:'Wi-Fi zone updated',detail:'C Block · Floor 2 · STU1024',tone:'cyan'},
 ]);
 const [requests,setRequests] = useState([
  {id:'REQ-2048',studentId:'STU1024',studentName:'Srinesh G',course:'Machine Learning',faculty:'Dr. Meena',time:'10:34 AM',status:'Awaiting review',zone:'C Block · Floor 2',reason:'Absent from class but reported on campus',cameraActive:false},
  {id:'REQ-2047',studentId:'STU1029',studentName:'Harish V',course:'Neural Networks',faculty:'Prof. Arun',time:'10:12 AM',status:'Closed',zone:'A Block · Floor 1',reason:'Student location requested',cameraActive:false},
 ]);
 const [currentRequest,setCurrentRequest] = useState(null);
 const [cameraSessions,setCameraSessions] = useState([]);
 const [showProfile,setShowProfile] = useState(false);
 const filteredStudents = useMemo(()=>students.filter(s=>{
   const q=query.toLowerCase();
   const matches = [s.name,s.id,s.dept,s.zone].some(v=>v.toLowerCase().includes(q));
   const status = filter==='All students' || (filter==='On campus'&&s.campus) || (filter==='Off campus'&&!s.campus) || (filter==='Attendance mismatch'&&s.campus&&s.attendance==='Absent'&&!s.duty) || (filter==='On duty'&&s.duty);
   return matches&&status;
 }),[students,query,filter]);
 const mismatchCount = students.filter(s=>s.campus&&s.attendance==='Absent'&&!s.duty).length;
 const onlineCount = students.filter(s=>s.campus).length;
 function notify(message){setToast(message);window.setTimeout(()=>setToast(''),3200);}
 function updateStudent(id,patch){setStudents(prev=>prev.map(s=>s.id===id?{...s,...patch}:s)); if(selected.id===id)setSelected({...selected,...patch});}
 function markAttendance(id,status){updateStudent(id,{attendance:status,duty:status==='On Duty'});setActivity(prev=>[{time:new Date().toLocaleTimeString('en-US',{hour12:false}),title:`Attendance marked ${status}`,detail:`${id} · Manually recorded by ${role.toLowerCase()}`,tone:status==='Present'?'green':status==='On Duty'?'violet':'amber'},...prev]);notify(`Attendance updated: ${id} → ${status}`);}
 function requestLocation(student,reason=requestReason){
   const req={id:`REQ-${Math.floor(2050+Math.random()*8000)}`,studentId:student.id,studentName:student.name,course:'Current class / subject',faculty:role==='Admin'?'Campus Admin':'Current faculty',time:new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'}),status:'Awaiting review',zone:student.zone,reason,cameraActive:false};
   setRequests(prev=>[req,...prev]);setCurrentRequest(req);setSelected(student);setModal({type:'location',student,request:req});
   setActivity(prev=>[{time:new Date().toLocaleTimeString('en-US',{hour12:false}),title:'Location request created',detail:`${student.id} · Camera processing remains OFF until authorized confirmation`,tone:'blue'},...prev]);
 }
 function activateReview(req){
   const next={...req,status:'Authorized review in progress',cameraActive:true};
   setRequests(prev=>prev.map(r=>r.id===req.id?next:r));setCurrentRequest(next);
   setCameraSessions(prev=>[{id:req.id,studentId:req.studentId,studentName:req.studentName,zone:req.zone,status:'Active review',started:new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'}),owner:role},...prev]);
   setActivity(prev=>[{time:new Date().toLocaleTimeString('en-US',{hour12:false}),title:'Camera review authorized',detail:`${req.studentId} · Scoped review · Demo mode only`,tone:'amber'},...prev]);
   setModal({type:'camera',student:students.find(s=>s.id===req.studentId)||selected,request:next});
   notify('Demo camera review started. No physical CCTV is connected.');
 }
 function closeReview(req){
   setRequests(prev=>prev.map(r=>r.id===req.id?{...r,status:'Closed',cameraActive:false}:r));
   setCameraSessions(prev=>prev.map(c=>c.id===req.id?{...c,status:'Ended'}:c));
   setActivity(prev=>[{time:new Date().toLocaleTimeString('en-US',{hour12:false}),title:'Camera review ended',detail:`${req.studentId} · Review session closed`,tone:'green'},...prev]);
   setModal(null);notify('Location review closed.');
 }
 function applyPoint(id){const s=students.find(x=>x.id===id);if(!s)return;setModal({type:'points',student:s});}
 function confirmPoint(id){updateStudent(id,{points:Math.max(0,(students.find(x=>x.id===id)?.points||0)-1)});setActivity(prev=>[{time:new Date().toLocaleTimeString('en-US',{hour12:false}),title:'Point deduction recorded',detail:`${id} · Requires faculty confirmation`,tone:'rose'},...prev]);setModal(null);notify('Demo point deduction recorded.');}
 function exportCsv(){const rows=[['Student ID','Name','Department','Campus status','Attendance','On duty','Points','Last seen'],...students.map(s=>[s.id,s.name,s.dept,s.campus?'On campus':'Off campus',s.attendance,s.duty?'Yes':'No',s.points,s.lastSeen])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='encontrar-campus-demo.csv';a.click();URL.revokeObjectURL(url);notify('CSV export prepared.');}
 function handleNav(label){setPage(label);setSidebarOpen(false);setQuery('');}

 return <div className="app-shell">
  <aside className={`sidebar ${sidebarOpen?'open':''}`}>
   <div className="brand"><div className="brand-mark"><MapPin size={21} strokeWidth={2.7}/></div><div className="brand-name">encontrar<span>.</span><small>CAMPUS INTELLIGENCE</small></div><button className="icon-btn mobile-close" onClick={()=>setSidebarOpen(false)}><X size={18}/></button></div>
   <div className="workspace-select"><div className="workspace-avatar">RG</div><div><strong>Rathinam Global</strong><span>Campus workspace</span></div><ChevronDown size={15}/></div>
   <div className="nav-scroll">{navGroups.map(group=><div className="nav-group" key={group.label}><div className="nav-label">{group.label}</div>{group.items.map(([label,Icon])=><button key={label} className={`nav-item ${page===label?'active':''}`} onClick={()=>handleNav(label)}><Icon size={17}/><span>{label}</span>{label==='Location requests'&&requests.filter(r=>r.status==='Awaiting review').length>0&&<b className="nav-count">{requests.filter(r=>r.status==='Awaiting review').length}</b>}</button>)}</div>)}</div>
   <div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><LifeBuoy size={17}/></div><div><strong>Need a hand?</strong><span>Campus ops guide</span></div><ChevronRight size={14}/></div><div className="user-block"><Avatar student={{initials:'SG',color:'violet'}}/><div className="user-meta"><strong>Srinesh G</strong><span>{role} account</span></div><button className="icon-btn" onClick={()=>setShowProfile(v=>!v)}><MoreHorizontal size={18}/></button>{showProfile&&<div className="profile-popover"><span>Preview role</span><button onClick={()=>{setRole('Faculty');setShowProfile(false)}}>Faculty</button><button onClick={()=>{setRole('Admin');setShowProfile(false)}}>Administrator</button><button onClick={()=>{setRole('Student');setShowProfile(false)}}>Student (view only)</button></div>}</div></div>
  </aside>
  {sidebarOpen&&<div className="mobile-scrim" onClick={()=>setSidebarOpen(false)}/>}
  <main className="main-area">
   <header className="topbar"><div className="topbar-left"><button className="icon-btn mobile-menu" onClick={()=>setSidebarOpen(true)}><Menu size={20}/></button><div className="breadcrumb">Campus / <strong>{page}</strong></div><span className="environment-pill"><i/> DEMO ENVIRONMENT</span></div><div className="topbar-right"><div className="search-global"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search students, ID, department…"/><kbd>⌘ K</kbd></div><button className="icon-btn notification-btn" onClick={()=>{setPage('Location requests');notify('Showing active campus requests.')}}><Bell size={18}/><i/></button><div className="top-divider"/><button className="profile-trigger" onClick={()=>setShowProfile(v=>!v)}><Avatar student={{initials:'SG',color:'violet'}}/><span><strong>Srinesh G</strong><small>{role}</small></span><ChevronDown size={14}/></button></div></header>
   <div className="content-area">
    {page==='Overview'&&<>
      <div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/> CAMPUS OPERATIONS <span className="eyebrow-sep">/</span> FRIDAY, 09 OCTOBER</div><h1>Good morning, Srinesh <span>✦</span></h1><p>Here’s what’s happening across your campus today.</p></div><div className="heading-actions"><button className="btn btn-secondary" onClick={exportCsv}><Download size={15}/> Export report</button><button className="btn btn-primary" onClick={()=>setPage('Location requests')}><LocateFixed size={16}/> Review requests <span className="btn-counter">{requests.filter(r=>r.status==='Awaiting review').length}</span></button></div></div>
      <div className="stat-grid">
       <StatCard title="Students on campus" value={onlineCount.toLocaleString()} change="Live demo snapshot" icon={Users} color="blue" footer={`${students.length} enrolled in this demo`} trend="stable"/>
       <StatCard title="Attendance recorded" value="91.4%" change="+2.6% vs yesterday" icon={ClipboardCheck} color="green" footer="Staff-marked · 1,284 records" trend="up"/>
       <StatCard title="Attendance mismatches" value={String(mismatchCount).padStart(2,'0')} change="Needs faculty review" icon={AlertCircle} color="amber" footer="On-campus + marked absent + not on duty" trend="warn"/>
       <StatCard title="Location requests" value={String(requests.filter(r=>r.status==='Awaiting review').length).padStart(2,'0')} change="Camera remains OFF by default" icon={LocateFixed} color="violet" footer={`${cameraSessions.filter(c=>c.status==='Active review').length} active review sessions`} trend="stable"/>
      </div>
      <div className="overview-grid">
       <Panel className="attendance-panel"><PanelHead title="Attendance overview" sub="Staff-recorded attendance across the campus" action={<select className="select-small" value={range} onChange={e=>setRange(e.target.value)}><option>Today</option><option>This week</option><option>This month</option></select>}/><div className="chart-legend"><span><i className="legend-dot present"/> Present</span><span><i className="legend-dot absent"/> Absent</span><span className="legend-caption">Updated 2 min ago</span></div><div className="attendance-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={weekly} margin={{top:8,right:8,bottom:0,left:-20}}><defs><linearGradient id="presentFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2e9b7c" stopOpacity={0.2}/><stop offset="100%" stopColor="#2e9b7c" stopOpacity={0.01}/></linearGradient></defs><CartesianGrid stroke="#e9edf3" vertical={false}/><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{fill:'#8c96a8',fontSize:11}} dy={10}/><YAxis domain={[0,100]} tickLine={false} axisLine={false} tick={{fill:'#8c96a8',fontSize:11}} tickFormatter={v=>`${v}%`}/><Tooltip contentStyle={{border:'1px solid #e7ebf1',borderRadius:12,fontSize:12}} formatter={(v,n)=>[`${v}%`,n==='present'?'Present':'Absent']}/><Area type="monotone" dataKey="present" stroke="#2e9b7c" strokeWidth={2.5} fill="url(#presentFill)"/><Area type="monotone" dataKey="absent" stroke="#e4a14a" strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer></div><div className="chart-bottom"><div><span className="mini-label">ATTENDANCE COMPLETION</span><strong>91.4%</strong></div><div className="progress-track"><span style={{width:'91.4%'}}/></div><span className="muted-tiny">Staff-marked only</span></div></Panel>
       <Panel className="entry-panel"><PanelHead title="Campus activity" sub="RFID entry / exit events" action={<button className="text-btn" onClick={()=>handleNav('Entry & exit')}>View logs <ArrowRight size={14}/></button>}/><div className="entry-summary"><div><span>ENTRY EVENTS</span><strong>1,120</strong><small><ArrowDownRight size={12}/> 8.2% vs yesterday</small></div><div className="entry-ring"><div className="ring-inner"><strong>87%</strong><span>of expected</span></div></div></div><div className="sparkline-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="entryFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6e7bf1" stopOpacity={0.28}/><stop offset="100%" stopColor="#6e7bf1" stopOpacity={0}/></linearGradient></defs><Area type="monotone" dataKey="entries" stroke="#7d89f7" strokeWidth={2} fill="url(#entryFill)"/></AreaChart></ResponsiveContainer></div><div className="entry-foot"><span><i className="status-dot green-dot"/> Reader network operational</span><span>Last sync 10:35 AM</span></div></Panel>
      </div>
      <div className="lower-grid"><Panel className="mismatch-panel"><PanelHead title="Needs your attention" sub="Potential discrepancies for human review" action={<button className="text-btn" onClick={()=>{setFilter('Attendance mismatch');setPage('Student directory')}}>View all <ArrowRight size={14}/></button>}/><div className="table-wrap"><table><thead><tr><th>STUDENT</th><th>LAST OBSERVED</th><th>ATTENDANCE</th><th>STATUS</th><th/></tr></thead><tbody>{students.filter(s=>s.campus&&s.attendance==='Absent'&&!s.duty).slice(0,4).map(s=><tr key={s.id}><td><div className="student-cell"><Avatar student={s}/><div><strong>{s.name}</strong><small>{s.id} · {s.dept}</small></div></div></td><td><div className="zone-cell">{s.zone}<small>{s.lastSeen} · {s.confidence} confidence</small></div></td><td><Badge tone="amber">Absent</Badge></td><td><Badge tone="blue" dot>Review suggested</Badge></td><td><button className="row-action" title="Request location" onClick={()=>requestLocation(s)}><LocateFixed size={16}/></button></td></tr>)}</tbody></table></div><div className="panel-footer"><Shield size={14}/> A mismatch is a review prompt, not a confirmed violation.</div></Panel>
       <Panel className="activity-panel"><PanelHead title="Recent activity" sub="Latest system and staff events" action={<button className="icon-btn mini" onClick={()=>handleNav('Activity logs')}><MoreHorizontal size={18}/></button>}/><div className="activity-list">{activity.slice(0,5).map((a,i)=><div className="activity-row" key={i}><div className={`activity-icon ${a.tone}`}>{a.tone==='green'?<Check size={15}/>:a.tone==='amber'?<AlertCircle size={15}/>:a.tone==='violet'?<ShieldCheck size={15}/>:a.tone==='cyan'?<Wifi size={15}/>:<LocateFixed size={15}/>}</div><div className="activity-text"><strong>{a.title}</strong><span>{a.detail}</span></div><time>{a.time}</time></div>)}</div><button className="activity-link" onClick={()=>handleNav('Activity logs')}>View activity log <ArrowRight size={14}/></button></Panel>
      </div>
      <div className="system-strip"><div className="system-strip-title"><div className="system-icon"><ShieldCheck size={18}/></div><div><strong>All core systems operational</strong><span>Last system health check · 10:35:42 AM</span></div></div><div className="system-chips"><span><i className="status-dot green-dot"/> RFID readers <b>4/4</b></span><span><i className="status-dot green-dot"/> Wi-Fi feed <b>Connected (demo)</b></span><span><i className="status-dot slate-dot"/> CCTV analytics <b>Standby</b></span><span><i className="status-dot slate-dot"/> ML model <b>Not connected</b></span></div><button className="text-btn" onClick={()=>handleNav('Integrations')}>System health <ArrowRight size={14}/></button></div>
    </>}
    {page==='Student directory'&&<Directory students={filteredStudents} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} onSelect={s=>{setSelected(s);setModal({type:'student',student:s})}} onRequest={requestLocation} onAttendance={markAttendance} onExport={exportCsv} role={role}/>}
    {page==='Attendance'&&<Attendance students={students} onMark={markAttendance} onExport={exportCsv} notify={notify}/>}
    {page==='Location requests'&&<Requests requests={requests} students={students} onStart={activateReview} onClose={closeReview} onSelect={r=>{setCurrentRequest(r);setSelected(students.find(s=>s.id===r.studentId)||selected);setModal({type:'location',student:students.find(s=>s.id===r.studentId)||selected,request:r})}}/>}
    {page==='Campus map'&&<CampusMap students={students} onSelect={s=>{setSelected(s);setModal({type:'student',student:s})}} onRequest={requestLocation}/>}
    {page==='Entry & exit'&&<Entries students={students} onExport={exportCsv}/>}
    {page==='Camera access'&&<CameraAccess requests={requests} sessions={cameraSessions} onStart={activateReview} onClose={closeReview} role={role}/>}
    {page==='Points & policies'&&<Points students={students} onApply={applyPoint} notify={notify}/>}
    {page==='Activity logs'&&<ActivityLogs activity={activity}/>}
    {page==='Integrations'&&<Integrations notify={notify}/>}
    {page==='Settings'&&<SettingsPage role={role} setRole={setRole} alerts={alerts} setAlerts={setAlerts} notify={notify}/>}
    <footer className="app-footer"><span>© 2026 Encontrar · Campus Intelligence</span><span><i className="status-dot slate-dot"/> Prototype · Demo data only</span><span>Privacy-first workflows <ShieldCheck size={13}/></span></footer>
   </div>
  </main>
  {toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}<button onClick={()=>setToast('')}><X size={14}/></button></div>}
  {modal&&<Modal modal={modal} students={students} role={role} setModal={setModal} setRequestReason={setRequestReason} requestReason={requestReason} requestLocation={requestLocation} activateReview={activateReview} closeReview={closeReview} onPoint={confirmPoint} onNotify={notify} onMark={markAttendance}/>}
 </div>;
}

function StatCard({title,value,change,icon:Icon,color,footer,trend}){return <Panel className="stat-card"><div className="stat-top"><div className={`stat-icon ${color}`}><Icon size={19}/></div><button className="icon-btn mini"><MoreHorizontal size={17}/></button></div><div className="stat-title">{title}</div><div className="stat-value">{value}</div><div className={`stat-change ${trend}`}>{trend==='up'?<ArrowDownRight size={13}/>:trend==='warn'?<AlertCircle size={13}/>:<CircleDot size={12}/>} {change}</div><div className="stat-footer">{footer}</div></Panel>}

function Directory({students,query,setQuery,filter,setFilter,onSelect,onRequest,onAttendance,onExport,role}){return <><PageHeader eyebrow="PEOPLE & RECORDS" title="Student directory" sub="Roster, campus status, staff attendance and review actions." action={<button className="btn btn-secondary" onClick={onExport}><Download size={15}/> Export CSV</button>}/><Panel><div className="directory-toolbar"><div className="search-field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, ID, department…"/></div><select className="select-small" value={filter} onChange={e=>setFilter(e.target.value)}><option>All students</option><option>On campus</option><option>Off campus</option><option>Attendance mismatch</option><option>On duty</option></select><span className="muted-tiny">{students.length} records</span></div><div className="table-wrap full-table"><table><thead><tr><th>STUDENT</th><th>DEPARTMENT</th><th>CAMPUS STATUS</th><th>CLASS ATTENDANCE</th><th>LAST OBSERVATION</th><th>POINTS</th><th>ACTIONS</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td><button className="student-cell as-button" onClick={()=>onSelect(s)}><Avatar student={s}/><div><strong>{s.name}</strong><small>{s.id} · {s.year}</small></div></button></td><td><strong className="table-strong">{s.dept}</strong></td><td><Badge tone={s.campus?'green':'neutral'} dot>{s.campus?'On campus':'Off campus'}</Badge></td><td>{s.duty?<Badge tone="violet">On Duty</Badge>:<Badge tone={s.attendance==='Present'?'green':'amber'}>{s.attendance}</Badge>}</td><td><div className="zone-cell">{s.zone}<small>{s.lastSeen}</small></div></td><td><strong>{s.points}</strong><span className="muted-tiny"> / 100</span></td><td><div className="inline-actions"><button className="icon-btn mini" title="View record" onClick={()=>onSelect(s)}><Eye size={15}/></button>{role!=='Student'&&<button className="icon-btn mini" title="Request location" onClick={()=>onRequest(s)}><LocateFixed size={15}/></button>}</div></td></tr>)}</tbody></table>{students.length===0&&<EmptyState title="No students found" text="Try a different search or filter."/>}</div></Panel></>}

function Attendance({students,onMark,onExport,notify}){const [subject,setSubject]=useState('Machine Learning');const [section,setSection]=useState('AIML · II Sem');const [search,setSearch]=useState('');const [local,setLocal]=useState({});const list=students.filter(s=>`${s.name} ${s.id} ${s.dept}`.toLowerCase().includes(search.toLowerCase()));return <><PageHeader eyebrow="ACADEMIC OPERATIONS" title="Classroom attendance" sub="Attendance is recorded by teaching staff. No face recognition is used to mark attendance." action={<button className="btn btn-secondary" onClick={onExport}><Download size={15}/> Export roster</button>}/><div className="notice info"><ClipboardCheck size={18}/><div><strong>Staff-controlled attendance</strong><span>Present, Absent and On Duty are recorded manually. On Duty is exempt from absence alerts and point deductions.</span></div></div><Panel><div className="attendance-toolbar"><div className="field-group"><label>Subject</label><select value={subject} onChange={e=>setSubject(e.target.value)}><option>Machine Learning</option><option>Deep Learning</option><option>Data Structures</option><option>Computer Networks</option></select></div><div className="field-group"><label>Class / section</label><select value={section} onChange={e=>setSection(e.target.value)}><option>AIML · II Sem</option><option>AIML · I Sem</option><option>CSE · II Sem</option><option>ECE · III Sem</option></select></div><div className="field-group"><label>Date</label><div className="date-pill"><CalendarDays size={15}/> 09 Oct 2026</div></div><div className="search-field attendance-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find student"/></div></div><div className="table-wrap full-table"><table><thead><tr><th>STUDENT</th><th>STATUS</th><th>MARK ATTENDANCE</th></tr></thead><tbody>{list.map(s=>{const status=local[s.id]|| (s.duty?'On Duty':s.attendance);return <tr key={s.id}><td><div className="student-cell"><Avatar student={s}/><div><strong>{s.name}</strong><small>{s.id} · {s.dept}</small></div></div></td><td><Badge tone={status==='Present'?'green':status==='On Duty'?'violet':'amber'}>{status}</Badge></td><td><div className="attendance-toggle">{['Present','Absent','On Duty'].map(v=><button key={v} className={`${status===v?'selected ':''}${v==='Present'?'good':v==='Absent'?'bad':'duty'}`} onClick={()=>setLocal(p=>({...p,[s.id]:v}))}>{v}</button>)}</div></td></tr>})}</tbody></table></div><div className="form-actions"><span className="muted-tiny">{Object.keys(local).length} changes not yet saved</span><button className="btn btn-primary" onClick={()=>{Object.entries(local).forEach(([id,v])=>onMark(id,v));setLocal({});notify('Attendance changes saved to demo state.')}}><Check size={15}/> Save attendance</button></div></Panel></>}

function Requests({requests,students,onStart,onClose,onSelect}){const [tab,setTab]=useState('All requests');const shown=requests.filter(r=>tab==='All requests'||(tab==='Needs review'&&r.status==='Awaiting review')||(tab==='Active reviews'&&r.status==='Authorized review in progress')||(tab==='Closed'&&r.status==='Closed'));return <><PageHeader eyebrow="AUTHORIZED LOCATION LOOKUP" title="Location requests" sub="Camera analytics stays idle until an authorized faculty member or administrator starts a scoped review." action={<Badge tone="neutral" dot>Camera processing off by default</Badge>}/><div className="notice caution"><ShieldCheck size={18}/><div><strong>Privacy gate enabled</strong><span>A request alone does not turn on a camera. A permitted operator must explicitly start a review; demo controls do not connect to physical CCTV.</span></div></div><Panel><div className="tabs">{['All requests','Needs review','Active reviews','Closed'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}<span>{requests.filter(r=>t==='All requests'||(t==='Needs review'&&r.status==='Awaiting review')||(t==='Active reviews'&&r.status==='Authorized review in progress')||(t==='Closed'&&r.status==='Closed')).length}</span></button>)}</div><div className="request-list">{shown.map(req=>{const s=students.find(x=>x.id===req.studentId)||initialStudents[0];return <div className="request-row" key={req.id}><Avatar student={s} size="lg"/><div className="request-main"><div className="request-title"><strong>{req.studentName}</strong><code>{req.studentId}</code><Badge tone={req.status==='Awaiting review'?'amber':req.status==='Authorized review in progress'?'blue':'green'} dot>{req.status}</Badge></div><p>{req.reason}</p><div className="request-meta"><span><BookOpen size={13}/>{req.course}</span><span><UserRound size={13}/>{req.faculty}</span><span><Clock3 size={13}/>{req.time}</span><span><MapPin size={13}/>{req.zone}</span></div></div><div className="request-actions"><button className="btn btn-secondary compact" onClick={()=>onSelect(req)}>Details</button>{req.status==='Awaiting review'?<button className="btn btn-primary compact" onClick={()=>onStart(req)}><Camera size={14}/> Start review</button>:req.status==='Authorized review in progress'?<button className="btn btn-danger compact" onClick={()=>onClose(req)}><Ban size={14}/> End review</button>:<Badge tone="green"><Check size={12}/> Closed</Badge>}</div></div>})}{shown.length===0&&<EmptyState title="Nothing in this queue" text="Requests matching this filter will appear here."/>}</div></Panel></>}

function CampusMap({students,onSelect,onRequest}){const [zone,setZone]=useState('All zones');const zones=['All zones','Main Building','A Block','C Block','Library','Canteen'];const filtered=students.filter(s=>zone==='All zones'||s.zone===zone);return <><PageHeader eyebrow="CAMPUS INTELLIGENCE" title="Campus map" sub="Zone-level observations are estimates. Live facial analysis is only requested through an authorized lookup." action={<Badge tone="neutral"><MapPin size={12}/> Demo map</Badge>}/><div className="map-layout"><Panel className="map-panel"><div className="map-toolbar"><div><strong>Rathinam campus</strong><span>Illustrative zone layout · not a live GIS feed</span></div><select className="select-small" value={zone} onChange={e=>setZone(e.target.value)}>{zones.map(z=><option key={z}>{z}</option>)}</select></div><div className="campus-illustration"><div className="map-path path-one"/><div className="map-path path-two"/><div className="map-building main-building"><span>Main Building</span><small>Teaching & administration</small></div><div className="map-building ablock"><span>A Block</span><small>Engineering</small></div><div className="map-building cblock"><span>C Block</span><small>AIML · CSE</small></div><div className="map-building library"><span>Library</span><small>Academic resources</small></div><div className="map-building canteen"><span>Canteen</span><small>Dining area</small></div><div className="map-building hostel"><span>Hostel</span></div>{filtered.filter(s=>s.campus).map((s,i)=><button key={s.id} className={`map-pin pin-${i%6}`} title={`${s.name} · ${s.zone}`} onClick={()=>onSelect(s)}><MapPin size={18}/><span>{s.initials}</span></button>)}<div className="map-legend"><span><i className="legend-dot present"/> On campus (demo)</span><span><i className="legend-dot absent"/> Attendance mismatch</span><span><i className="legend-dot neutral"/> Zone estimate</span></div></div></Panel><Panel className="zone-list-panel"><PanelHead title="Zone observations" sub={`${filtered.filter(s=>s.campus).length} students in current view`}/><div className="zone-student-list">{filtered.filter(s=>s.campus).map(s=><div className="zone-student" key={s.id}><Avatar student={s}/><div className="zone-student-main"><strong>{s.name}</strong><span>{s.id} · {s.zone}</span><small>Last observed {s.lastSeen}</small></div><div className="zone-student-actions">{s.attendance==='Absent'&&!s.duty?<Badge tone="amber">Mismatch</Badge>:<Badge tone="green">{s.duty?'On duty':s.attendance}</Badge>}<button className="icon-btn mini" title="Request location" onClick={()=>onRequest(s)}><LocateFixed size={14}/></button></div></div>)}</div><div className="notice subtle"><CircleHelp size={16}/><span>Map pins are simulated observations for UI testing and do not represent actual student locations.</span></div></Panel></div></>}

function Entries({students,onExport}){const [tab,setTab]=useState('All events');const events=students.slice(0,5).map((s,i)=>({id:s.id,name:s.name,event:i%3===2?'Exit detected':'Entry detected',reader:i%3===2?'North Exit Gate':'Main Gate · Portal 01',time:['10:31:02 AM','10:26:42 AM','10:19:08 AM','10:14:55 AM','10:07:31 AM'][i],status:i===2?'Exit':'Entry'}));const shown=events.filter(e=>tab==='All events'||e.status===tab);return <><PageHeader eyebrow="ACCESS OPERATIONS" title="Entry & exit" sub="Passive UHF RFID portal events, with no facial recognition at campus gates." action={<button className="btn btn-secondary" onClick={onExport}><Download size={15}/> Export logs</button>}/><div className="stat-grid small-stats"><StatCard title="Entry events today" value="1,120" change="RFID portal demo" icon={DoorOpen} color="blue" footer="All portals combined" trend="stable"/><StatCard title="Exit events today" value="284" change="RFID portal demo" icon={ArrowRight} color="violet" footer="All exits combined" trend="stable"/><StatCard title="Reader status" value="4 / 4" change="Nominal (simulated)" icon={RadioTower} color="green" footer="Reader heartbeat placeholder" trend="up"/></div><Panel><div className="tabs">{['All events','Entry','Exit'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="table-wrap full-table"><table><thead><tr><th>TIME</th><th>STUDENT</th><th>EVENT</th><th>READER / GATE</th><th>MODE</th></tr></thead><tbody>{shown.map(e=><tr key={`${e.id}-${e.time}`}><td><strong className="table-strong">{e.time}</strong></td><td><div className="student-cell"><Avatar student={students.find(s=>s.id===e.id)}/><div><strong>{e.name}</strong><small>{e.id}</small></div></div></td><td><Badge tone={e.status==='Entry'?'green':'neutral'} dot>{e.event}</Badge></td><td>{e.reader}</td><td><Badge tone="blue">Passive UHF RFID</Badge></td></tr>)}</tbody></table></div></Panel></>}

function CameraAccess({requests,sessions,onStart,onClose,role}){return <><PageHeader eyebrow="PRIVACY & ACCESS CONTROL" title="Camera access" sub="No continuous face search. Camera analytics should run only for an explicitly requested, authorized location review." action={<Badge tone="neutral" dot>Standby by default</Badge>}/><div className="camera-state-card"><div className="camera-big-icon"><Camera size={26}/><span/></div><div className="camera-state-text"><Badge tone="green" dot>Default state · Standby</Badge><h2>Camera analysis is not running</h2><p>Campus CCTV keeps its normal security function; identity matching is not initiated by this dashboard unless an authorized, scoped request is approved.</p><div className="camera-guardrails"><span><CheckCircle2 size={14}/> Explicit faculty/admin request</span><span><CheckCircle2 size={14}/> Reason recorded</span><span><CheckCircle2 size={14}/> Auditable start & stop</span></div></div></div><div className="two-panels"><Panel><PanelHead title="Requests awaiting review" sub="Only requested locations can enter this workflow"/><div className="request-compact-list">{requests.filter(r=>r.status==='Awaiting review').map(r=><div className="request-compact" key={r.id}><div><strong>{r.studentName}</strong><span>{r.studentId} · {r.reason}</span><small>{r.time} · {r.faculty}</small></div><button className="btn btn-primary compact" onClick={()=>onStart(r)}><Camera size={14}/> Review</button></div>)}{requests.filter(r=>r.status==='Awaiting review').length===0&&<EmptyState title="No pending requests" text="New authorized requests appear here."/>}</div></Panel><Panel><PanelHead title="Review session history" sub="Scoped sessions shown for demo purposes"/><div className="session-list">{sessions.map(s=><div className="session-row" key={s.id}><div className="session-status"><i className={s.status==='Active review'?'active':''}/></div><div className="session-main"><strong>{s.studentName} · {s.studentId}</strong><span>{s.zone} · Started {s.started} · {s.owner}</span></div><Badge tone={s.status==='Active review'?'amber':'green'}>{s.status}</Badge></div>)}{sessions.length===0&&<EmptyState title="No review sessions yet" text="No camera review has been started in this session."/>}</div></Panel></div><Panel><PanelHead title="Access safeguards" sub="Recommended production requirements"/><div className="guardrail-grid"><Guard title="Role-based authorization" text="Only permitted faculty/admin accounts can request and start a lookup."/><Guard title="Purpose limitation" text="Each request captures a reason and targets one student and a limited time window."/><Guard title="Audit trail" text="Record operator, reason, camera scope, start/stop timestamps and outcome."/><Guard title="Human verification" text="A model's candidate match must be reviewed; do not automate a disciplinary decision."/></div></Panel></>}

function Points({students,onApply,notify}){return <><PageHeader eyebrow="POLICY MANAGEMENT" title="Points & policies" sub="Configurable policy for reviewed attendance discrepancies. Demo values only." action={<button className="btn btn-secondary" onClick={()=>notify('Policy editor is a prototype placeholder.')}><Settings size={15}/> Configure policy</button>}/><div className="notice caution"><AlertCircle size={18}/><div><strong>No automatic deductions</strong><span>Location evidence can be uncertain. This prototype requires explicit staff confirmation before changing points.</span></div></div><div className="stat-grid small-stats"><StatCard title="Average points" value="89.2" change="Across demo roster" icon={ChartNoAxesCombined} color="blue" footer="Out of 100 points" trend="stable"/><StatCard title="Pending review" value={String(students.filter(s=>s.campus&&s.attendance==='Absent'&&!s.duty).length)} change="Potential mismatch cases" icon={AlertCircle} color="amber" footer="Must be reviewed manually" trend="warn"/><StatCard title="Exempt records" value={String(students.filter(s=>s.duty).length)} change="On Duty / official work" icon={ShieldCheck} color="green" footer="No points deduction" trend="up"/></div><Panel><PanelHead title="Student points ledger" sub="Use deduct only after a verified, policy-compliant decision."/><div className="table-wrap full-table"><table><thead><tr><th>STUDENT</th><th>ATTENDANCE</th><th>CAMPUS</th><th>POINTS</th><th>POLICY STATUS</th><th>ACTION</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td><div className="student-cell"><Avatar student={s}/><div><strong>{s.name}</strong><small>{s.id}</small></div></div></td><td>{s.duty?<Badge tone="violet">On Duty</Badge>:<Badge tone={s.attendance==='Present'?'green':'amber'}>{s.attendance}</Badge>}</td><td><Badge tone={s.campus?'green':'neutral'}>{s.campus?'On campus':'Off campus'}</Badge></td><td><strong>{s.points}</strong> <span className="muted-tiny">/100</span><div className="points-bar"><i style={{width:`${s.points}%`}}/></div></td><td>{s.duty?<Badge tone="green">Exempt</Badge>:s.campus&&s.attendance==='Absent'?<Badge tone="amber">Review first</Badge>:<Badge tone="neutral">No action</Badge>}</td><td><button className="btn btn-secondary compact" disabled={s.duty} onClick={()=>onApply(s.id)}>Record decision</button></td></tr>)}</tbody></table></div></Panel></>}

function ActivityLogs({activity}){return <><PageHeader eyebrow="AUDIT & OBSERVABILITY" title="Activity logs" sub="Chronological record of dashboard actions. Production logs should be server-side and tamper-evident." action={<button className="btn btn-secondary" onClick={()=>window.print()}><Download size={15}/> Print log</button>}/><Panel><div className="panel-head"><div><h3>Latest events</h3><p>Newest events first · Demo session</p></div><Badge tone="neutral">{activity.length} events</Badge></div><div className="audit-list">{activity.map((a,i)=><div className="audit-row" key={i}><time>{a.time}</time><div className={`audit-dot ${a.tone}`}/><div><strong>{a.title}</strong><p>{a.detail}</p></div><Badge tone="neutral">UI event</Badge></div>)}</div></Panel></>}

function Integrations({notify}){const integrations=[{name:'UHF RFID gate readers',detail:'Entry / exit tag observations',status:'Demo adapter',icon:RadioTower,color:'blue'},{name:'Wi-Fi location feed',detail:'Access-point association / zone estimates',status:'Not connected',icon:Wifi,color:'violet'},{name:'CCTV / VMS',detail:'On-demand camera stream request only',status:'Standby',icon:Camera,color:'amber'},{name:'ML inference service',detail:'Campus presence / attendance context / lookup decision',status:'Waiting for model',icon:Activity,color:'green'},{name:'ZKTeco access control',detail:'Access terminals and FBL700 barriers',status:'Not connected',icon:ShieldCheck,color:'blue'},{name:'Student information system',detail:'Roster, course and faculty mapping',status:'Demo dataset',icon:GraduationCap,color:'rose'}];return <><PageHeader eyebrow="SYSTEM CONFIGURATION" title="Integrations" sub="Adapters are separated so hardware and the forthcoming ML model can be integrated without redesigning the dashboard." action={<Badge tone="neutral">5 placeholders</Badge>}/><div className="integration-grid">{integrations.map(i=><Panel className="integration-card" key={i.name}><div className={`integration-icon ${i.color}`}><i.icon size={20}/></div><Badge tone={i.status==='Demo adapter'||i.status==='Demo dataset'?'blue':i.status==='Standby'?'amber':'neutral'} dot>{i.status}</Badge><h3>{i.name}</h3><p>{i.detail}</p><button className="btn btn-secondary full-btn" onClick={()=>notify(`${i.name}: configuration will be added when integration details are available.`)}>Configure <ChevronRight size={14}/></button></Panel>)}</div><Panel><PanelHead title="Model integration contract" sub="Recommended REST boundary for your teammate's ML component"/><div className="api-contract"><div className="api-line"><span className="http-method">POST</span><code>/api/v1/location-requests/evaluate</code><Badge tone="neutral">Proposed</Badge></div><p>Input: student ID, campus-presence context, staff attendance state, on-duty status, faculty request state and authorized operator. Output: decision to keep analytics off, request an authorized review, or return a candidate location with timestamp and confidence. The model must not independently mark attendance or deduct points.</p><div className="api-line"><span className="http-method get">GET</span><code>/api/v1/health</code><Badge tone="neutral">Proposed</Badge></div><p>Health endpoint for the future inference service. Current dashboard uses a local demo adapter and sends no real identity or camera data.</p></div></Panel></>}

function SettingsPage({role,setRole,alerts,setAlerts,notify}){return <><PageHeader eyebrow="PREFERENCES & ACCESS" title="Settings" sub="Prototype settings for role previews and workflow defaults."/><div className="two-panels"><Panel><PanelHead title="Access & role" sub="Demo role selector; production should use SSO/RBAC."/><div className="settings-row"><div><strong>Preview role</strong><span>Changes which actions are shown in the interface.</span></div><select className="select-small" value={role} onChange={e=>{setRole(e.target.value);notify(`Preview role changed to ${e.target.value}.`)}}><option>Faculty</option><option>Admin</option><option>Student</option></select></div><div className="settings-row"><div><strong>Camera activation policy</strong><span>On-demand only; explicit request and authorized operator.</span></div><Badge tone="green">Enforced in demo UI</Badge></div><div className="settings-row"><div><strong>Attendance source</strong><span>Manual staff entry; not camera-generated.</span></div><Badge tone="blue">Staff controlled</Badge></div></Panel><Panel><PanelHead title="Notifications" sub="Local prototype notification preferences."/><div className="settings-row"><div><strong>Attendance mismatch alerts</strong><span>Flag students marked absent while their campus status is on.</span></div><button className={`toggle ${alerts?'on':''}`} onClick={()=>setAlerts(v=>!v)}><i/></button></div><div className="settings-row"><div><strong>Location review updates</strong><span>Show changes to faculty-requested reviews.</span></div><button className="toggle on" onClick={()=>notify('Review update setting is demo-only.') }><i/></button></div></Panel></div><Panel><PanelHead title="Security baseline" sub="To implement before any real deployment"/><div className="guardrail-grid"><Guard title="Authentication" text="Use institutional SSO/MFA and secure sessions; never rely on UI-only roles."/><Guard title="Authorization" text="Check every request on the server for operator, purpose, scope and permission."/><Guard title="Data minimization" text="Store the least location and biometric metadata needed; define deletion windows."/><Guard title="Auditability" text="Log who requests a lookup, which system is activated, and when processing stops."/></div></Panel></>}

function Modal({modal,students,role,setModal,setRequestReason,requestReason,requestLocation,activateReview,closeReview,onPoint,onNotify,onMark}){const s=modal.student;const req=modal.request;const [reason,setReason]=useState(requestReason);const [confirmed,setConfirmed]=useState(false);const [dutyReason,setDutyReason]=useState('');if(!modal)return null;return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className="modal-card"><div className="modal-head"><div><span className="eyebrow">{modal.type==='camera'?'ON-DEMAND CAMERA REVIEW':modal.type==='location'?'AUTHORIZED LOCATION REQUEST':modal.type==='points'?'POINTS DECISION':'STUDENT RECORD'}</span><h2>{modal.type==='points'?'Review point decision':modal.type==='camera'?'Scoped location review':modal.type==='location'?'Request student location':s.name}</h2></div><button className="icon-btn" onClick={()=>setModal(null)}><X size={18}/></button></div>
 {modal.type==='location'&&<><div className="modal-student"><Avatar student={s} size="lg"/><div><strong>{s.name}</strong><span>{s.id} · {s.dept} · {s.year}</span><div className="modal-badges"><Badge tone={s.campus?'green':'neutral'}>{s.campus?'On campus (reported)':'Off campus (reported)'}</Badge><Badge tone={s.duty?'violet':s.attendance==='Present'?'green':'amber'}>{s.duty?'On Duty':s.attendance}</Badge></div></div></div><div className="location-context"><div><span>Last zone estimate</span><strong>{s.zone}</strong></div><div><span>Last observed</span><strong>{s.lastSeen}</strong></div><div><span>Signal confidence</span><strong>{s.confidence}</strong></div></div><div className="field-group full"><label>Reason for request</label><select value={reason} onChange={e=>{setReason(e.target.value);setRequestReason(e.target.value)}}><option>Absent from class but reported on campus</option><option>Student welfare check</option><option>Authorized campus security request</option><option>Other approved institutional purpose</option></select></div><div className="notice caution compact-notice"><ShieldCheck size={17}/><span>Creating a request does not activate facial recognition. An authorized operator must explicitly start the scoped review.</span></div><div className="modal-actions"><button className="btn btn-secondary" onClick={()=>setModal(null)}>Cancel</button><button className="btn btn-primary" onClick={()=>{setRequestReason(reason);requestLocation(s,reason);setModal(null);onNotify('Location request created. Camera remains on standby.')}}><LocateFixed size={15}/> Create request</button></div></>}
 {modal.type==='camera'&&<><div className="notice caution"><Camera size={18}/><div><strong>Demo camera review</strong><span>This does not connect to actual CCTV or run real facial recognition. Production must obtain authorization from the server before camera access.</span></div></div><div className="camera-preview"><div className="preview-grid"><div className="preview-camera"><Camera size={30}/><strong>CAM-C2-03</strong><span>Corridor · C Block / Floor 2</span><Badge tone="amber" dot>Simulated preview</Badge></div><div className="preview-target"><Avatar student={s} size="xl"/><strong>{s.name}</strong><span>{s.id}</span><Badge tone="neutral">Demo record · Not a match result</Badge></div></div><div className="preview-footer"><span><i className="status-dot amber-dot"/> Session active in demo mode</span><span>Started just now</span></div></div><div className="field-group full"><label>Review outcome (demo)</label><select><option>No verified observation yet</option><option>Candidate observed — requires human verification</option><option>Unable to locate in available footage</option><option>Escalate for welfare check</option></select></div><div className="modal-actions"><button className="btn btn-secondary" onClick={()=>closeReview(req)}>End review</button><button className="btn btn-primary" onClick={()=>{onNotify('Demo review note saved.');setModal(null)}}><Check size={15}/> Save review note</button></div></>}
 {modal.type==='points'&&<><div className="modal-student"><Avatar student={s} size="lg"/><div><strong>{s.name}</strong><span>{s.id} · Current points {s.points}/100</span><div className="modal-badges">{s.duty?<Badge tone="violet">On Duty exemption</Badge>:<Badge tone="amber">Attendance: {s.attendance}</Badge>}</div></div></div>{s.duty?<div className="notice info"><ShieldCheck size={17}/><span>This student is marked On Duty. A deduction is blocked by the current policy.</span></div>:<><p className="modal-copy">You are about to record a one-point deduction in demo state. Confirm the attendance record and follow the institution's review/appeal policy first.</p><label className="checkbox-row"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I confirm the attendance record was reviewed by authorized staff.</label></>}<div className="modal-actions"><button className="btn btn-secondary" onClick={()=>setModal(null)}>Cancel</button><button className="btn btn-danger" disabled={s.duty||!confirmed} onClick={()=>onPoint(s.id)}><AlertCircle size={15}/> Confirm −1 point</button></div></>}
 {modal.type==='student'&&<><div className="student-profile-modal"><Avatar student={s} size="xl"/><div><h3>{s.name}</h3><p>{s.id} · {s.dept} · {s.year}</p><div className="modal-badges"><Badge tone={s.campus?'green':'neutral'}>{s.campus?'On campus':'Off campus'}</Badge><Badge tone={s.duty?'violet':s.attendance==='Present'?'green':'amber'}>{s.duty?'On Duty':s.attendance}</Badge></div></div></div><div className="profile-detail-grid"><div><span>Last observed zone</span><strong>{s.zone}</strong></div><div><span>Time</span><strong>{s.lastSeen}</strong></div><div><span>Observation source</span><strong>{s.source}</strong></div><div><span>Current points</span><strong>{s.points}/100</strong></div></div><div className="modal-actions"><button className="btn btn-secondary" onClick={()=>setModal(null)}>Close</button>{role!=='Student'&&<button className="btn btn-primary" onClick={()=>{requestLocation(s);setModal(null)}}><LocateFixed size={15}/> Request location</button>}</div></>}
 </div></div>}

function PageHeader({eyebrow,title,sub,action}){return <div className="page-heading inner-page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div>{action&&<div className="heading-actions">{action}</div>}</div>}
function EmptyState({title,text}){return <div className="empty-state"><div><Search size={22}/></div><strong>{title}</strong><span>{text}</span></div>}
function Guard({title,text}){return <div className="guardrail"><div><ShieldCheck size={17}/></div><section><strong>{title}</strong><p>{text}</p></section></div>}
