import React, { useMemo, useState } from 'react';
import { Activity, AlertTriangle, BookOpen, Check, LocateFixed, MessageSquare, Phone, Search, ShieldAlert, Users, Clock3, X } from 'lucide-react';
const seed=[
{id:'STU1024',name:'Srinesh G',department:'AIML',year:'II Year',attendance:'Absent',campus:true,classPresent:false,zone:'C Block · Floor 2',lastSeen:'10:24 AM',gate:'North Gate',points:0},
{id:'STU1025',name:'Kavin R',department:'CSE',year:'II Year',attendance:'Present',campus:true,classPresent:true,zone:'A Block · Room 101',lastSeen:'10:31 AM',gate:'North Gate',points:0},
{id:'STU1026',name:'Divya S',department:'AIML',year:'I Year',attendance:'On Duty',campus:true,classPresent:false,zone:'Library · Floor 3',lastSeen:'10:18 AM',gate:'South Gate',points:0},
{id:'STU1027',name:'Arjun M',department:'ECE',year:'III Year',attendance:'Present',campus:true,classPresent:true,zone:'C Block · Room 202',lastSeen:'10:33 AM',gate:'South Gate',points:0},
{id:'STU1028',name:'Nithya P',department:'IT',year:'II Year',attendance:'Absent',campus:false,classPresent:false,zone:'Last seen: Main Gate',lastSeen:'9:06 AM',gate:'North Gate',points:1},
{id:'STU1029',name:'Harish V',department:'AIML',year:'III Year',attendance:'Present',campus:true,classPresent:false,zone:'A Block · Floor 1',lastSeen:'10:28 AM',gate:'North Gate',points:0}];
const initials=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2);
export default function App(){
const [students,setStudents]=useState(seed),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[checks,setChecks]=useState({}),[active,setActive]=useState(null),[message,setMessage]=useState(''),[notice,setNotice]=useState(''),[pointsReason,setPointsReason]=useState('Unexplained class absence'),[pointsToAdd,setPointsToAdd]=useState('1'),[loading,setLoading]=useState({}),[logs,setLogs]=useState([{time:'10:34 AM',text:'Dashboard ready',detail:'Sample records loaded · live hardware not connected'}]);
const visible=useMemo(()=>students.filter(s=>(s.id+' '+s.name+' '+s.department).toLowerCase().includes(query.toLowerCase())&&(filter==='All'||s.attendance===filter)),[students,query,filter]);
const addLog=(text,detail)=>setLogs(old=>[{time:new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}),text,detail},...old].slice(0,8));
const update=(id,patch)=>setStudents(old=>old.map(s=>s.id===id?{...s,...patch}:s));
const notify=text=>{setNotice(text);setTimeout(()=>setNotice(''),2800)};
async function mark(s,status){update(s.id,{attendance:status});addLog('Attendance marked '+status,s.id+' · Staff action');if(status!=='Absent'){setChecks(old=>({...old,[s.id]:null}));return}setLoading(old=>({...old,[s.id]:true}));setChecks(old=>({...old,[s.id]:null}));try{const response=await fetch('/api/attendance/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({student_id:s.id,department:s.department,year_of_study:parseInt(s.year)||2,attendance_status:'Absent'})});if(!response.ok)throw new Error('API unavailable');const result=await response.json();setChecks(old=>({...old,[s.id]:result}));addLog('Attendance check completed',s.id+' · '+result.reason)}catch{const demo={student_id:s.id,status:'demo_only',model_available:false,campus_present:s.campus,class_present:s.classPresent,zone:s.zone,last_seen:s.lastSeen,gate_id:s.gate,reason:s.campus?'Sample gate record indicates campus entry; class presence needs verification.':'No successful entry in sample gate data.',source:'Sample RFID events (not a live reader)'};setChecks(old=>({...old,[s.id]:demo}));addLog('Demo attendance check',s.id+' · Python API/model not connected')}finally{setLoading(old=>({...old,[s.id]:false}))}}
function doAction(type,student){setActive({type,student});if(type==='message')setMessage('');if(type==='points')setPointsToAdd('1');if(type==='location')addLog('Location details opened',student.id+' · Existing zone data only')}
function submitAction(){const type=active.type,s=active.student;if(type==='message'&&!message.trim())return;if(type==='points'){const n=Math.max(1,Math.min(10,Number(pointsToAdd)||1));update(s.id,{points:s.points+n});addLog('Violation points added',s.id+' · +'+n+' · '+pointsReason);notify(n+' point(s) added to '+s.id)}else if(type==='message'){addLog('Message drafted',s.id+' · '+message.trim());notify('Demo only: no message was sent.')}else if(type==='call')notify('Demo only: no phone call was placed.');setActive(null)}
const flagged=students.filter(s=>s.attendance==='Absent'&&checks[s.id]?.campus_present&&!checks[s.id]?.class_present);
return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-logo">e</div><div><strong>encontrar<span>.</span></strong><small>FACULTY DASHBOARD</small></div></div><div className="side-label">WORKSPACE</div><div className="side-active"><Activity size={17}/> Attendance & students</div><div className="side-note"><ShieldAlert size={17}/><span><b>Privacy-first workflow</b><small>Check gate records first. Faculty initiates follow-up.</small></span></div><div className="side-bottom"><span className="online-dot"/> Local demo environment</div></aside>
<main className="main"><header className="topbar"><div><div className="crumb">Campus / <b>Attendance</b></div><h1>Student attendance</h1><p>Mark attendance, verify gate records, and follow up when needed.</p></div><div className="faculty"><div className="faculty-avatar">FM</div><div><b>Faculty Member</b><small>Faculty access</small></div></div></header><section className="content">
<div className="stats"><div className="stat"><span className="stat-icon blue"><Users size={18}/></span><div><small>Students shown</small><strong>{students.length}</strong></div></div><div className="stat"><span className="stat-icon green"><Check size={18}/></span><div><small>Present</small><strong>{students.filter(s=>s.attendance==='Present').length}</strong></div></div><div className="stat"><span className="stat-icon amber"><AlertTriangle size={18}/></span><div><small>Absent</small><strong>{students.filter(s=>s.attendance==='Absent').length}</strong></div></div><div className="stat"><span className="stat-icon violet"><LocateFixed size={18}/></span><div><small>Needs follow-up</small><strong>{flagged.length}</strong></div></div></div>
<div className="workflow"><div className="workflow-icon"><Activity size={19}/></div><div><b>How it works</b><p>Choose <b>Absent</b> to check gate-entry data. If the student appears to be on campus but not in class, follow-up actions appear beside attendance.</p></div><span className="demo-pill">Model / RFID status shown per check</span></div>
<div className="toolbar"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, student ID, department"/></div><div className="filters">{['All','Present','Absent','On Duty'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></div>
<div className="table-card"><div className="table-scroll"><table><thead><tr><th>STUDENT</th><th>DEPARTMENT</th><th>ATTENDANCE STATUS</th><th>GATE / LAST SEEN</th><th>FOLLOW-UP ACTIONS</th></tr></thead><tbody>{visible.map(s=>{const c=checks[s.id];const mismatch=s.attendance==='Absent'&&c?.campus_present&&!c?.class_present;return <React.Fragment key={s.id}><tr><td><div className="student"><div className="student-avatar">{initials(s.name)}</div><div><b>{s.name}</b><small>{s.id} · {s.year}</small></div></div></td><td><span className="dept">{s.department}</span></td><td><div className="status-buttons">{['Present','Absent','On Duty'].map(status=><button key={status} disabled={loading[s.id]} className={status.toLowerCase().replace(' ','-')+(s.attendance===status?' chosen':'')} onClick={()=>mark(s,status)}>{status}</button>)}</div>{loading[s.id]&&<small className="checking"><span className="spinner"/> Checking gate + ML signals…</small>}{c&&<div className={'result '+(c.model_available?'':'demo-result')}><span className="result-dot"/><span>{c.model_available?'ML result':'DEMO CHECK'} · {c.campus_present?'Campus entry found':'No confirmed campus entry'}{c.campus_present&&!c.class_present?' · Not in class':''}</span></div>}</td><td><div className="last-seen"><b>{s.gate}</b><small><Clock3 size={12}/>{s.lastSeen}</small><small>{s.zone}</small></div></td><td>{mismatch?<div className="actions"><button className="action-btn location" onClick={()=>doAction('location',s)}><LocateFixed size={14}/> Location</button><button className="action-btn" title="Call" onClick={()=>doAction('call',s)}><Phone size={14}/></button><button className="action-btn" title="Message" onClick={()=>doAction('message',s)}><MessageSquare size={14}/></button><button className="action-btn points" onClick={()=>doAction('points',s)}><ShieldAlert size={14}/> Points</button></div>:<span className="muted">{s.attendance==='On Duty'?'Duty exemption':s.attendance==='Absent'?(c?'No campus mismatch found':'Mark absent to check'):'No action required'}</span>}</td></tr>{mismatch&&<tr className="detail-row"><td colSpan="5"><div className="detail-banner"><LocateFixed size={15}/><div><b>{s.name} may be on campus but outside the scheduled class</b><small>{c.zone||s.zone} · Last seen {c.last_seen||s.lastSeen} · {c.reason||'Faculty review required.'}</small></div><span className={c.model_available?'model-tag':'demo-tag'}>{c.model_available?'ML RESULT':'DEMO DATA'}</span></div></td></tr>}</React.Fragment>})}</tbody></table>{visible.length===0&&<div className="empty">No students match this search.</div>}</div><div className="table-footer"><span>Showing {visible.length} of {students.length} students</span><span><span className="online-dot"/> Attendance changes are local to this demo</span></div></div>
<div className="bottom-grid"><section className="card"><div className="card-heading"><div><h2>Recent activity</h2><p>Latest attendance and follow-up events</p></div><Activity size={17}/></div>{logs.slice(0,5).map((l,i)=><div className="log" key={i}><span className="log-dot"/><div><b>{l.text}</b><small>{l.detail}</small></div><time>{l.time}</time></div>)}</section><section className="card"><div className="card-heading"><div><h2>Integration status</h2><p>Current environment, not hardware health</p></div><BookOpen size={17}/></div><div className="integration"><span className="integration-led demo"/>Python ML API <b>Check status in backend</b></div><div className="integration"><span className="integration-led demo"/>RFID gate reader <b>Sample data only</b></div><div className="integration"><span className="integration-led off"/>SMS / calling <b>Not connected</b></div><div className="privacy-note">A mismatch is a prompt for faculty review, not proof of a violation. Location shows stored zone data only, not live GPS or a camera feed.</div></section></div></section></main>
{active&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setActive(null)}}><section className="modal"><div className="modal-head"><div><span className="modal-kicker">STUDENT FOLLOW-UP</span><h2>{active.type==='location'?'Location details':active.type==='call'?'Call student':active.type==='message'?'Send a message':'Add violation points'}</h2></div><button className="close" onClick={()=>setActive(null)}><X size={18}/></button></div><div className="modal-student"><div className="student-avatar big">{initials(active.student.name)}</div><div><b>{active.student.name}</b><small>{active.student.id} · {active.student.department} · {active.student.year}</small></div></div>
{active.type==='location'&&<><div className="location-grid"><div><small>Last known zone</small><b>{checks[active.student.id]?.zone||active.student.zone}</b></div><div><small>Last observation</small><b>{checks[active.student.id]?.last_seen||active.student.lastSeen}</b></div><div><small>Gate record</small><b>{checks[active.student.id]?.gate_id||active.student.gate}</b></div><div><small>Source</small><b>{checks[active.student.id]?.source||'Sample data'}</b></div></div><div className="notice-box">This is the last recorded zone, not live GPS or a live camera feed. Confirm details before taking action.</div></>}
{active.type==='call'&&<div className="notice-box">Calling is not connected in this demo. Connect an approved calling provider and verified contact details to enable real calls.</div>}
{active.type==='message'&&<label className="form-label">Message<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Please report to your faculty member regarding today's attendance…" rows="4"/></label>}
{active.type==='points'&&<><label className="form-label">Points to add<select value={pointsToAdd} onChange={e=>setPointsToAdd(e.target.value)}>{[1,2,3,5,10].map(n=><option key={n} value={n}>{n} point{n>1?'s':''}</option>)}</select></label><label className="form-label">Reason<select value={pointsReason} onChange={e=>setPointsReason(e.target.value)}><option>Unexplained class absence</option><option>Repeated late arrival</option><option>Faculty-reviewed policy violation</option><option>Other — faculty review</option></select></label><div className="notice-box">Points are added only after faculty confirmation. An ML result alone does not create a violation.</div></>}
<div className="modal-actions"><button className="cancel" onClick={()=>setActive(null)}>Cancel</button>{active.type!=='location'&&<button className="confirm" onClick={submitAction}>{active.type==='call'?'Confirm demo call':active.type==='message'?'Record message':'Add points'}</button>}{active.type==='location'&&<button className="confirm" onClick={()=>{addLog('Location details reviewed',active.student.id+' · Faculty opened location details');setActive(null);notify('Location details reviewed.')}}>Done</button>}</div></section></div>}
{notice&&<div className="toast"><Check size={16}/>{notice}</div>}</div>
}